version: 2.1

orbs:
  codecov: codecov/codecov@1.0.2

jobs:
  test:
    docker:
      - image: circleci/python:3.10-node
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: make init
      - run:
          name: Run static type checking
          command: make types
      - run:
          name: Run quality checks
          command: make quality
      - run:
          name: Run tests
          command: make test
      - codecov/upload:
          file: coverage.xml
  pypi_publish:
    docker:
      - image: circleci/python:3.10-node
    steps:
      - checkout
      - run:
          name: Upload to PyPi
          command: make pypi

workflows:
  test:
    jobs:
      - test
      - pypi_publish:
          requires:
            - test
          filters:
            branches:
              only:
                - main
